### ISSUE TITLE
Missing Surveys

### ISSUE THREAD

**Issue by anpa8** [DNNCommunity/DNN.Survey#47]
Hi,
is it possible, that some surveys where deleted when upgrade ?

Some users missing surveys they have created. Can't reproduce it.
Or exists an autodelete of old surveys? 
DNN9.5.0
Regards,
Angelo

**Comment by MaiklT** [comment]
There is no autodelete, and I upgraded a lot of surveys during testing without a problem, so I cannot reproduce this behaviour. Do you have more information?

**Comment by anpa8** [comment]
Sorry, i don't have any information.
The module is on the page, but without questions etc. And all of the users, which have write access, told me, that they don't deleted the questions. It Looks like that the database tables from survey where cleaned up...

**Comment by anpa8** [comment]
Again, all surveys are deleted, except the oldest. Don't know how this is going :(

**Comment by anpa8** [comment]
Now i can reproduce the problem in my testing-env.

for example:
i have 2 surveys on 2 different pages with 3 questions each.
on second survey i delete a question, then all questions of survey 1 are also deleted...

**Comment by anpa8** [comment]
Have Uploaded a video for this:
https://vm2.anpa-networks.de/index.php/s/uV8bTWnbWUtzmRf

**Comment by MaiklT** [comment]
OK, I could reproduce this, even more (eg changing the sort order od Survey 2 deletes Survey 1). Please let me some time to investigate this. Thank you.

**Comment by MaiklT** [comment]
OK, here is a quick fix for this. Open the attached file in Settings >> SQL Console and run the script.
[Fix.txt](https://github.com/DNNCommunity/DNN.Survey/files/4673183/Fix.txt)

The issue will be fixed in DNN Survey 09.01.00.

**Comment by anpa8** [comment]
Thank you very much. Works fine.

**Comment by MaiklT** [comment]
Please don't close before it is fixed. This workaround might help others who have the same issue. Thanks.

**Comment by anpa8** [comment]
Oh, okay. Sorry. Now i know it for the next time :)

**Comment by Timo-Breumelhof** [comment]
@MaiklT does running the SQL script fix the module or only the current state?

**Comment by Timo-Breumelhof** [comment]
FYI, the script did not fix my issue, all surveys remain empty..

**Comment by Timo-Breumelhof** [comment]
Ok I now see all but one

**Comment by wbonekamp** [comment]
Same problem here... no surveys in database... all deleted
Why is this bug still present in the latest version (after 6 months)? 
Can you please release a new version with the fix?

**Comment by MaiklT** [comment]
Sorry for the delay.
The problem is fixed, just run the query in my comment from May, 24 above ([Fix.txt](https://github.com/DNNCommunity/DNN.Survey/files/4673183/Fix.txt))

**Comment by wbonekamp** [comment]
It did the trick but is the fix also implemented in the current version of the module?

Users that install the module still have the issue and will find out when all data is gone...

**Comment by MaiklT** [comment]
Again, sorry for the delay, I don't want to discuss the reasons in public.
The bug is fixed in version 9.1.0, which will be available soon (I hope). It affects only installations with more than one survey.

**Comment by valadas** [comment]
Fixed in shortly upcoming 9.1.0
